name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci || npm install --no-fund --no-audit
        
      - name: Update next.config.js
        run: |
          cat > next.config.js << 'EOL'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            basePath: '/CV-Website-Aug2025',
            assetPrefix: '/CV-Website-Aug2025/',
            trailingSlash: true,
            images: {
              domains: ["images.unsplash.com"],
              unoptimized: true,
            },
            experimental: {
              optimizeCss: true,
            },
          };
          
          module.exports = nextConfig;
          EOL
          
      - name: Build
        run: npx next build
        
      - name: Fix index.html (temporary)
        run: |
          if [ ! -f "out/index.html" ] || grep -q "page.tsx" "out/index.html"; then
            cat > out/index.html << 'EOL'
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Darren O'Donnell - Interactive CV</title>
                <style>
                  body {
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    height: 100vh;
                    margin: 0;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                  }
                  .container {
                    text-align: center;
                    padding: 2rem;
                    max-width: 800px;
                  }
                  h1 {
                    font-size: 2.5rem;
                    margin-bottom: 0.5rem;
                  }
                  .content {
                    background: rgba(255, 255, 255, 0.1);
                    border-radius: 10px;
                    padding: 2rem;
                    margin-top: 2rem;
                  }
                  .message {
                    margin-top: 2rem;
                    padding: 1rem;
                    background: rgba(255, 255, 255, 0.2);
                    border-radius: 5px;
                  }
                </style>
              </head>
              <body>
                <div class="container">
                  <h1>Darren O'Donnell</h1>
                  <p>Interactive CV Website</p>
                  
                  <div class="content">
                    <h2>Welcome to my CV Website</h2>
                    <p>This site is currently under construction.</p>
                    
                    <div class="message">
                      <p>The complete interactive CV is coming soon!</p>
                      <p>This is a temporary placeholder while deployment issues are being resolved.</p>
                    </div>
                  </div>
                </div>
              </body>
            </html>
            EOL
          fi
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
